### ISSUE TITLE
Long double libmath support

### ISSUE THREAD

**Issue by dvdfreitag** [reswitched/libtransistor#54]
libcxx requires [long double support](https://github.com/llvm-mirror/libcxx/blob/master/include/math.h#L819), but newlib does not implement it. There is a stubbed implementation which just calls the double version of the function, for example: [cosl](https://github.com/reswitched/newlib/blob/master/newlib/libm/common/cosl.c#L37).

There are a few options to resolve this issue:

1. Make sure `_LDBL_EQ_DBL` is defined, and fake long double support with newlib's existing stubs. This will truncate all 128-bit floats to 64-bit floats.
2. Either find or implement a libmath that will include the necessary long double support
3. Modify newlib and implement the missing functions alongside the existing stubs

**Comment by dvdfreitag** [comment]
Judging by my tests both 1 and 3 will require modifications to the newlib source tree. The problem is that newlib uses a recursive make and any variables defined when calling `configure` or `make` are not carried into the libm build.

An ugly hack could be to use sed to replace a line in the generated `newlib.h` file between calling `configure` and `make`.

**Comment by misson20000** [comment]
Is this resolved with openlibm?

**Comment by dvdfreitag** [comment]
Yes, the only thing that openlibm did not solve was the dependency on `strtold`, but as I recall @roblabla made some modifications to newlib so that this is fixed. The WIP c++ builds without encapsulating stdlib

**Comment by roblabla** [comment]
No modifications to newlib, just added a missing include dir in the libtransistor.mk

On February 1, 2018 3:46:40 PM GMT+01:00, David Freitag <notifications@github.com> wrote:
>Yes, the only thing that openlibm did not solve was the dependency on
>`strtold`, but as I recall @roblabla made some modifications to newlib
>so that this is fixed. The WIP c++ builds without encapsulating stdlib
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/reswitched/libtransistor/issues/54#issuecomment-362287238

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
